export const offices = [
  { id: 1, name: 'Aaron W.', size: 'small', people: [{ name: 'Aaron Wadhwa', avatar: '/headshots/aaron-wadhwa.jpg' }] },
  { id: 2, name: 'Arnav B.', size: 'small', people: [{ name: 'Arnav Bansal', avatar: '/headshots/arnav-bansal.jpg' }] },
  { id: 3, name: 'Ava L.', size: 'small', people: [{ name: 'Ava Lee', avatar: '/headshots/ava-lee.jpg' }] },
  { id: 4, name: 'Chelsea T.', size: 'small', people: [{ name: 'Chelsea Turbin', avatar: '/headshots/chelsea-turbin.jpg' }] },
  { id: 5, name: 'Derek C.', size: 'small', people: [{ name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg' }] },
  { id: 6, name: 'Garima K.', size: 'small', people: [{ name: 'Garima Kewlani', avatar: '/headshots/garima-kewlani.jpg' }] },
  { id: 7, name: 'Grace S.', size: 'small', people: [{ name: 'Grace Sutherland', avatar: '/headshots/grace-sutherland.jpg' }] },
  { id: 8, name: 'Howard L.', size: 'small', people: [{ name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg' }] },
  { id: 10, name: 'Jeff G.', size: 'small', people: [{ name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg' }] },
  { id: 11, name: 'Joe W.', size: 'small', people: [{ name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg' }] },
  { id: 12, name: 'John B.', size: 'small', people: [{ name: 'John Beutner', avatar: '/headshots/john-beutner.jpg' }] },
  { id: 13, name: 'John H.', size: 'small', people: [{ name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg' }] },
  { id: 14, name: 'John M.', size: 'small', people: [{ name: 'John Moffa', avatar: '/headshots/john-moffa.jpg' }] },
  { id: 15, name: 'Jon B.', size: 'small', people: [{ name: 'Jon Brod', avatar: '/headshots/jon-brod.jpg' }] },
  { id: 16, name: 'Keegan L.', size: 'small', people: [{ name: 'Keegan Lanzillotta', avatar: '/headshots/keegan-lanzillotta.jpg' }] },
  { id: 18, name: 'Lexi B.', size: 'small', people: [{ name: 'Lexi Bohonnon', avatar: '/headshots/lexi-bohonnon.jpg' }] },
  { id: 19, name: 'Mattias L.', size: 'small', people: [{ name: 'Mattias Leino', avatar: '/headshots/mattias-leino.jpg' }] },
  { id: 20, name: 'Klas L.', size: 'small', people: [{ name: 'Klas Leino', avatar: '/headshots/klas-leino.jpg' }] },
  { id: 21, name: 'Michael M.', size: 'small', people: [{ name: 'Michael Miller', avatar: '/headshots/michael-miller.jpg' }] },
  { id: 22, name: 'Michael W.', size: 'small', people: [{ name: 'Michael Walrath', avatar: '/headshots/michael-walrath.jpg' }] },
  { id: 23, name: 'Peter L.', size: 'small', people: [{ name: 'Peter Lerman', avatar: '/headshots/peter-lerman.jpg' }] },
  { id: 24, name: 'Rob F.', size: 'small', people: [{ name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg' }] },
  { id: 25, name: 'Sean M.', size: 'small', people: [{ name: 'Sean MacIsaac', avatar: '/headshots/sean-macisaac.jpg' }] },
  { id: 27, name: 'Thomas G.', size: 'small', people: [{ name: 'Thomas Grapperon', avatar: '/headshots/thomas-grapperon.jpg' }] },
  { id: 28, name: 'Tom D.', size: 'small', people: [{ name: 'Tom Dixon', avatar: '/headshots/tom-dixon.jpg' }] },
  // Video-talent roster
  { id: 101, name: 'Ashley B.', size: 'small', people: [{ name: 'Ashley Brooks', avatar: '/videos/Female/ashley_brooks.png', video: '/videos/Female/ashley_brooks.mp4' }] },
  { id: 102, name: 'Brooke F.', size: 'small', people: [{ name: 'Brooke Foster', avatar: '/videos/Female/brooke_foster.png', video: '/videos/Female/brooke_foster.mp4' }] },
  { id: 103, name: 'Camila T.', size: 'small', people: [{ name: 'Camila Torres', avatar: '/videos/Female/camila_torres.png', video: '/videos/Female/camila_torres.mp4' }] },
  { id: 104, name: 'Chloe P.', size: 'small', people: [{ name: 'Chloe Peterson', avatar: '/videos/Female/chloe_peterson.png', video: '/videos/Female/chloe_peterson.mp4' }] },
  { id: 105, name: 'Emily C.', size: 'small', people: [{ name: 'Emily Carter', avatar: '/videos/Female/emily_carter.png', video: '/videos/Female/emily_carter.mp4' }] },
  { id: 106, name: 'Grace T.', size: 'small', people: [{ name: 'Grace Thompson', avatar: '/videos/Female/grace_thompson.png', video: '/videos/Female/grace_thompson.mp4' }] },
  { id: 107, name: 'Hannah B.', size: 'small', people: [{ name: 'Hannah Bennett', avatar: '/videos/Female/hannah_bennett.png', video: '/videos/Female/hannah_bennett.mp4' }] },
  { id: 108, name: 'Isabella M.', size: 'small', people: [{ name: 'Isabella Morgan', avatar: '/videos/Female/isabella_morgan.png', video: '/videos/Female/isabella_morgan.mp4' }] },
  { id: 109, name: 'Jessica H.', size: 'small', people: [{ name: 'Jessica Hall', avatar: '/videos/Female/jessica_hall.png', video: '/videos/Female/jessica_hall.mp4' }] },
  { id: 110, name: 'Lauren H.', size: 'small', people: [{ name: 'Lauren Hayes', avatar: '/videos/Female/lauren_hayes.png', video: '/videos/Female/lauren_hayes.mp4' }] },
  { id: 111, name: 'Madison R.', size: 'small', people: [{ name: 'Madison Reed', avatar: '/videos/Female/madison_reed.png', video: '/videos/Female/madison_reed.mp4' }] },
  { id: 112, name: 'Megan T.', size: 'small', people: [{ name: 'Megan Taylor', avatar: '/videos/Female/megan_taylor.png', video: '/videos/Female/megan_taylor.mp4' }] },
  { id: 113, name: 'Mia C.', size: 'small', people: [{ name: 'Mia Chen', avatar: '/videos/Female/mia_chen.png', video: '/videos/Female/mia_chen.mp4' }] },
  { id: 114, name: 'Natalie W.', size: 'small', people: [{ name: 'Natalie Wilson', avatar: '/videos/Female/natalie_wilson.png', video: '/videos/Female/natalie_wilson.mp4' }] },
  { id: 115, name: 'Olivia S.', size: 'small', people: [{ name: 'Olivia Sanders', avatar: '/videos/Female/olivia_sanders.png', video: '/videos/Female/olivia_sanders.mp4' }] },
  { id: 116, name: 'Rachel C.', size: 'small', people: [{ name: 'Rachel Cooper', avatar: '/videos/Female/rachel_cooper.png', video: '/videos/Female/rachel_cooper.mp4' }] },
  { id: 117, name: 'Sarah M.', size: 'small', people: [{ name: 'Sarah Mitchell', avatar: '/videos/Female/sarah_mitchell.png', video: '/videos/Female/sarah_mitchell.mp4' }] },
  { id: 118, name: 'Sophia R.', size: 'small', people: [{ name: 'Sophia Ramirez', avatar: '/videos/Female/sophia_ramirez.png', video: '/videos/Female/sophia_ramirez.mp4' }] },
  { id: 119, name: 'Daniel R.', size: 'small', people: [{ name: 'Daniel Russell', avatar: '/videos/Male/daniel_russell.png', video: '/videos/Male/daniel_russell.mp4' }] },
  { id: 120, name: 'Ethan B.', size: 'small', people: [{ name: 'Ethan Bishop', avatar: '/videos/Male/ethan_bishop.png', video: '/videos/Male/ethan_bishop.mp4' }] },
  { id: 121, name: 'Michael S.', size: 'small', people: [{ name: 'Michael Stevens', avatar: '/videos/Male/michael_stevens.png', video: '/videos/Male/michael_stevens.mp4' }] },
];

// Shared video-talent roster for meeting-room/theater crowds
export const VIDEO_PEOPLE = [
  { name: 'Ashley Brooks', avatar: '/videos/Female/ashley_brooks.png', video: '/videos/Female/ashley_brooks.mp4' },
  { name: 'Brooke Foster', avatar: '/videos/Female/brooke_foster.png', video: '/videos/Female/brooke_foster.mp4' },
  { name: 'Camila Torres', avatar: '/videos/Female/camila_torres.png', video: '/videos/Female/camila_torres.mp4' },
  { name: 'Chloe Peterson', avatar: '/videos/Female/chloe_peterson.png', video: '/videos/Female/chloe_peterson.mp4' },
  { name: 'Emily Carter', avatar: '/videos/Female/emily_carter.png', video: '/videos/Female/emily_carter.mp4' },
  { name: 'Grace Thompson', avatar: '/videos/Female/grace_thompson.png', video: '/videos/Female/grace_thompson.mp4' },
  { name: 'Hannah Bennett', avatar: '/videos/Female/hannah_bennett.png', video: '/videos/Female/hannah_bennett.mp4' },
  { name: 'Isabella Morgan', avatar: '/videos/Female/isabella_morgan.png', video: '/videos/Female/isabella_morgan.mp4' },
  { name: 'Jessica Hall', avatar: '/videos/Female/jessica_hall.png', video: '/videos/Female/jessica_hall.mp4' },
  { name: 'Lauren Hayes', avatar: '/videos/Female/lauren_hayes.png', video: '/videos/Female/lauren_hayes.mp4' },
  { name: 'Madison Reed', avatar: '/videos/Female/madison_reed.png', video: '/videos/Female/madison_reed.mp4' },
  { name: 'Megan Taylor', avatar: '/videos/Female/megan_taylor.png', video: '/videos/Female/megan_taylor.mp4' },
  { name: 'Mia Chen', avatar: '/videos/Female/mia_chen.png', video: '/videos/Female/mia_chen.mp4' },
  { name: 'Natalie Wilson', avatar: '/videos/Female/natalie_wilson.png', video: '/videos/Female/natalie_wilson.mp4' },
  { name: 'Olivia Sanders', avatar: '/videos/Female/olivia_sanders.png', video: '/videos/Female/olivia_sanders.mp4' },
  { name: 'Rachel Cooper', avatar: '/videos/Female/rachel_cooper.png', video: '/videos/Female/rachel_cooper.mp4' },
  { name: 'Sarah Mitchell', avatar: '/videos/Female/sarah_mitchell.png', video: '/videos/Female/sarah_mitchell.mp4' },
  { name: 'Sophia Ramirez', avatar: '/videos/Female/sophia_ramirez.png', video: '/videos/Female/sophia_ramirez.mp4' },
  { name: 'Daniel Russell', avatar: '/videos/Male/daniel_russell.png', video: '/videos/Male/daniel_russell.mp4' },
  { name: 'Ethan Bishop', avatar: '/videos/Male/ethan_bishop.png', video: '/videos/Male/ethan_bishop.mp4' },
  { name: 'Michael Stevens', avatar: '/videos/Male/michael_stevens.png', video: '/videos/Male/michael_stevens.mp4' },
];

export const meetingRooms = [
  {
    id: 'war-room',
    name: 'War Room',
    size: 'large',
    gridIndex: 11,
    people: [
      { name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg', aiTool: 'claude' },
      { name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg', aiTool: 'claude' },
      { name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg', aiTool: 'claude' },
      { name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg', aiTool: 'claude' },
      { name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg', aiTool: 'claude' },
      { name: 'Will Hou', avatar: '/headshots/will-hou.jpg', aiTool: 'claude' },
      { name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg', aiTool: 'claude' },
    ]
  },
  {
    id: 'walt-disney',
    name: 'Walt Disney',
    size: 'large',
    crowd: true,
    people: (() => {
      const people = [
        { name: 'Aaron Wadhwa', avatar: '/headshots/aaron-wadhwa.jpg' },
        { name: 'Arnav Bansal', avatar: '/headshots/arnav-bansal.jpg' },
        { name: 'Ava Lee', avatar: '/headshots/ava-lee.jpg' },
        { name: 'Chelsea Turbin', avatar: '/headshots/chelsea-turbin.jpg' },
        { name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg' },
        { name: 'Garima Kewlani', avatar: '/headshots/garima-kewlani.jpg' },
        { name: 'Grace Sutherland', avatar: '/headshots/grace-sutherland.jpg' },
        { name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg' },
        { name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg' },
        { name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg' },
        { name: 'John Beutner', avatar: '/headshots/john-beutner.jpg' },
        { name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg' },
        { name: 'John Moffa', avatar: '/headshots/john-moffa.jpg' },
        { name: 'Jon Brod', avatar: '/headshots/jon-brod.jpg' },
        { name: 'Keegan Lanzillotta', avatar: '/headshots/keegan-lanzillotta.jpg' },
        { name: 'Lexi Bohonnon', avatar: '/headshots/lexi-bohonnon.jpg' },
        { name: 'Mattias Leino', avatar: '/headshots/mattias-leino.jpg' },
        { name: 'Klas Leino', avatar: '/headshots/klas-leino.jpg' },
        { name: 'Michael Miller', avatar: '/headshots/michael-miller.jpg' },
        { name: 'Michael Walrath', avatar: '/headshots/michael-walrath.jpg' },
        { name: 'Peter Lerman', avatar: '/headshots/peter-lerman.jpg' },
        { name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg' },
        { name: 'Sean MacIsaac', avatar: '/headshots/sean-macisaac.jpg' },
        { name: 'Thomas Grapperon', avatar: '/headshots/thomas-grapperon.jpg' },
        { name: 'Tom Dixon', avatar: '/headshots/tom-dixon.jpg' },
        { name: 'Will Hou', avatar: '/headshots/will-hou.jpg' },
        ...VIDEO_PEOPLE,
      ];
      return Array.from({ length: 200 }, (_, i) => ({
        ...people[i % people.length],
        displayName: people[i % people.length].name,
        name: `${people[i % people.length].name}_${i}`,
        aiTool: null,
      }));
    })(),
  },
  {
    id: 'alan-kay',
    name: 'Computer Department',
    size: 'large',
    crowd: true,
    theater: true,
    capacity: 1000,
    people: (() => {
      const people = [
        { name: 'Aaron Wadhwa', avatar: '/headshots/aaron-wadhwa.jpg' },
        { name: 'Arnav Bansal', avatar: '/headshots/arnav-bansal.jpg' },
        { name: 'Ava Lee', avatar: '/headshots/ava-lee.jpg' },
        { name: 'Chelsea Turbin', avatar: '/headshots/chelsea-turbin.jpg' },
        { name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg' },
        { name: 'Garima Kewlani', avatar: '/headshots/garima-kewlani.jpg' },
        { name: 'Grace Sutherland', avatar: '/headshots/grace-sutherland.jpg' },
        { name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg' },
        { name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg' },
        { name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg' },
        { name: 'John Beutner', avatar: '/headshots/john-beutner.jpg' },
        { name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg' },
        { name: 'John Moffa', avatar: '/headshots/john-moffa.jpg' },
        { name: 'Jon Brod', avatar: '/headshots/jon-brod.jpg' },
        { name: 'Keegan Lanzillotta', avatar: '/headshots/keegan-lanzillotta.jpg' },
        { name: 'Lexi Bohonnon', avatar: '/headshots/lexi-bohonnon.jpg' },
        { name: 'Mattias Leino', avatar: '/headshots/mattias-leino.jpg' },
        { name: 'Klas Leino', avatar: '/headshots/klas-leino.jpg' },
        { name: 'Michael Miller', avatar: '/headshots/michael-miller.jpg' },
        { name: 'Michael Walrath', avatar: '/headshots/michael-walrath.jpg' },
        { name: 'Peter Lerman', avatar: '/headshots/peter-lerman.jpg' },
        { name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg' },
        { name: 'Sean MacIsaac', avatar: '/headshots/sean-macisaac.jpg' },
        { name: 'Thomas Grapperon', avatar: '/headshots/thomas-grapperon.jpg' },
        { name: 'Tom Dixon', avatar: '/headshots/tom-dixon.jpg' },
        { name: 'Will Hou', avatar: '/headshots/will-hou.jpg' },
        ...VIDEO_PEOPLE,
      ];
      return Array.from({ length: 500 }, (_, i) => ({
        ...people[i % people.length],
        displayName: people[i % people.length].name,
        name: `ak_${people[i % people.length].name}_${i}`,
        aiTool: null,
      }));
    })(),
  }
];
