export const offices = [
  { id: 1, name: 'Aaron W.', size: 'small', people: [{ name: 'Aaron Wadhwa', avatar: '/headshots/aaron-wadhwa.jpg' }] },
  { id: 2, name: 'Arnav B.', size: 'small', people: [{ name: 'Arnav Bansal', avatar: '/headshots/arnav-bansal.jpg' }] },
  { id: 3, name: 'Ava L.', size: 'small', people: [{ name: 'Ava Lee', avatar: '/headshots/ava-lee.jpg' }] },
  { id: 4, name: 'Chelsea T.', size: 'small', people: [{ name: 'Chelsea Turbin', avatar: '/headshots/chelsea-turbin.jpg' }] },
  { id: 5, name: 'Derek C.', size: 'small', people: [{ name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg' }] },
  { id: 6, name: 'Garima K.', size: 'small', people: [{ name: 'Garima Kewlani', avatar: '/headshots/garima-kewlani.jpg' }] },
  { id: 7, name: 'Grace S.', size: 'small', people: [{ name: 'Grace Sutherland', avatar: '/headshots/grace-sutherland.jpg' }] },
  { id: 8, name: 'Howard L.', size: 'small', people: [{ name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg' }] },
  { id: 10, name: 'Jeff G.', size: 'small', people: [{ name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg' }] },
  { id: 11, name: 'Joe W.', size: 'small', people: [{ name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg' }] },
  { id: 12, name: 'John B.', size: 'small', people: [{ name: 'John Beutner', avatar: '/headshots/john-beutner.jpg' }] },
  { id: 13, name: 'John H.', size: 'small', people: [{ name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg' }] },
  { id: 14, name: 'John M.', size: 'small', people: [{ name: 'John Moffa', avatar: '/headshots/john-moffa.jpg' }] },
  { id: 15, name: 'Jon B.', size: 'small', people: [{ name: 'Jon Brod', avatar: '/headshots/jon-brod.jpg' }] },
  { id: 16, name: 'Keegan L.', size: 'small', people: [{ name: 'Keegan Lanzillotta', avatar: '/headshots/keegan-lanzillotta.jpg' }] },
  { id: 18, name: 'Lexi B.', size: 'small', people: [{ name: 'Lexi Bohonnon', avatar: '/headshots/lexi-bohonnon.jpg' }] },
  { id: 19, name: 'Mattias L.', size: 'small', people: [{ name: 'Mattias Leino', avatar: '/headshots/mattias-leino.jpg' }] },
  { id: 20, name: 'Klas L.', size: 'small', people: [{ name: 'Klas Leino', avatar: '/headshots/klas-leino.jpg' }] },
  { id: 21, name: 'Michael M.', size: 'small', people: [{ name: 'Michael Miller', avatar: '/headshots/michael-miller.jpg' }] },
  { id: 22, name: 'Michael W.', size: 'small', people: [{ name: 'Michael Walrath', avatar: '/headshots/michael-walrath.jpg' }] },
  { id: 23, name: 'Peter L.', size: 'small', people: [{ name: 'Peter Lerman', avatar: '/headshots/peter-lerman.jpg' }] },
  { id: 24, name: 'Rob F.', size: 'small', people: [{ name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg' }] },
  { id: 25, name: 'Sean M.', size: 'small', people: [{ name: 'Sean MacIsaac', avatar: '/headshots/sean-macisaac.jpg' }] },
  { id: 27, name: 'Thomas G.', size: 'small', people: [{ name: 'Thomas Grapperon', avatar: '/headshots/thomas-grapperon.jpg' }] },
  { id: 28, name: 'Tom D.', size: 'small', people: [{ name: 'Tom Dixon', avatar: '/headshots/tom-dixon.jpg' }] },
  { id: 30, name: 'Will H.', size: 'small', people: [{ name: 'Will Hou', avatar: '/headshots/will-hou.jpg' }] },
];

export const meetingRooms = [
  {
    id: 'war-room',
    name: 'War Room',
    size: 'large',
    gridIndex: 11,
    people: [
      { name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg', aiTool: 'claude' },
      { name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg', aiTool: 'claude' },
      { name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg', aiTool: 'claude' },
      { name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg', aiTool: 'claude' },
      { name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg', aiTool: 'claude' },
      { name: 'Will Hou', avatar: '/headshots/will-hou.jpg', aiTool: 'claude' },
      { name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg', aiTool: 'claude' },
    ]
  },
  {
    id: 'walt-disney',
    name: 'Walt Disney',
    size: 'large',
    crowd: true,
    people: (() => {
      const people = [
        { name: 'Aaron Wadhwa', avatar: '/headshots/aaron-wadhwa.jpg' },
        { name: 'Arnav Bansal', avatar: '/headshots/arnav-bansal.jpg' },
        { name: 'Ava Lee', avatar: '/headshots/ava-lee.jpg' },
        { name: 'Chelsea Turbin', avatar: '/headshots/chelsea-turbin.jpg' },
        { name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg' },
        { name: 'Garima Kewlani', avatar: '/headshots/garima-kewlani.jpg' },
        { name: 'Grace Sutherland', avatar: '/headshots/grace-sutherland.jpg' },
        { name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg' },
        { name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg' },
        { name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg' },
        { name: 'John Beutner', avatar: '/headshots/john-beutner.jpg' },
        { name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg' },
        { name: 'John Moffa', avatar: '/headshots/john-moffa.jpg' },
        { name: 'Jon Brod', avatar: '/headshots/jon-brod.jpg' },
        { name: 'Keegan Lanzillotta', avatar: '/headshots/keegan-lanzillotta.jpg' },
        { name: 'Lexi Bohonnon', avatar: '/headshots/lexi-bohonnon.jpg' },
        { name: 'Mattias Leino', avatar: '/headshots/mattias-leino.jpg' },
        { name: 'Klas Leino', avatar: '/headshots/klas-leino.jpg' },
        { name: 'Michael Miller', avatar: '/headshots/michael-miller.jpg' },
        { name: 'Michael Walrath', avatar: '/headshots/michael-walrath.jpg' },
        { name: 'Peter Lerman', avatar: '/headshots/peter-lerman.jpg' },
        { name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg' },
        { name: 'Sean MacIsaac', avatar: '/headshots/sean-macisaac.jpg' },
        { name: 'Thomas Grapperon', avatar: '/headshots/thomas-grapperon.jpg' },
        { name: 'Tom Dixon', avatar: '/headshots/tom-dixon.jpg' },
        { name: 'Will Hou', avatar: '/headshots/will-hou.jpg' },
      ];
      return Array.from({ length: 200 }, (_, i) => ({
        ...people[i % people.length],
        displayName: people[i % people.length].name,
        name: `${people[i % people.length].name}_${i}`,
        aiTool: null,
      }));
    })(),
  },
  {
    id: 'alan-kay',
    name: 'Alan Kay',
    size: 'large',
    crowd: true,
    theater: true,
    people: (() => {
      const people = [
        { name: 'Aaron Wadhwa', avatar: '/headshots/aaron-wadhwa.jpg' },
        { name: 'Arnav Bansal', avatar: '/headshots/arnav-bansal.jpg' },
        { name: 'Ava Lee', avatar: '/headshots/ava-lee.jpg' },
        { name: 'Chelsea Turbin', avatar: '/headshots/chelsea-turbin.jpg' },
        { name: 'Derek Cicerone', avatar: '/headshots/derek-cicerone.jpg' },
        { name: 'Garima Kewlani', avatar: '/headshots/garima-kewlani.jpg' },
        { name: 'Grace Sutherland', avatar: '/headshots/grace-sutherland.jpg' },
        { name: 'Howard Lerman', avatar: '/headshots/howard-lerman.jpg' },
        { name: 'Jeff Grossman', avatar: '/headshots/jeff-grossman.jpg' },
        { name: 'Joe Woodward', avatar: '/headshots/joe-woodward.jpg' },
        { name: 'John Beutner', avatar: '/headshots/john-beutner.jpg' },
        { name: 'John Huffsmith', avatar: '/headshots/john-huffsmith.jpg' },
        { name: 'John Moffa', avatar: '/headshots/john-moffa.jpg' },
        { name: 'Jon Brod', avatar: '/headshots/jon-brod.jpg' },
        { name: 'Keegan Lanzillotta', avatar: '/headshots/keegan-lanzillotta.jpg' },
        { name: 'Lexi Bohonnon', avatar: '/headshots/lexi-bohonnon.jpg' },
        { name: 'Mattias Leino', avatar: '/headshots/mattias-leino.jpg' },
        { name: 'Klas Leino', avatar: '/headshots/klas-leino.jpg' },
        { name: 'Michael Miller', avatar: '/headshots/michael-miller.jpg' },
        { name: 'Michael Walrath', avatar: '/headshots/michael-walrath.jpg' },
        { name: 'Peter Lerman', avatar: '/headshots/peter-lerman.jpg' },
        { name: 'Rob Figueiredo', avatar: '/headshots/rob-figueiredo.jpg' },
        { name: 'Sean MacIsaac', avatar: '/headshots/sean-macisaac.jpg' },
        { name: 'Thomas Grapperon', avatar: '/headshots/thomas-grapperon.jpg' },
        { name: 'Tom Dixon', avatar: '/headshots/tom-dixon.jpg' },
        { name: 'Will Hou', avatar: '/headshots/will-hou.jpg' },
      ];
      return Array.from({ length: 500 }, (_, i) => ({
        ...people[i % people.length],
        displayName: people[i % people.length].name,
        name: `ak_${people[i % people.length].name}_${i}`,
        aiTool: null,
      }));
    })(),
  }
];
