import { useEffect, useRef, useState } from 'react';
import Navbar from './Navbar';
import './RWNPage.css';

// ————————————————————————————————————————————————————————————————
// RWN — Remote Work News. A news hub owned by Roam.
// Sits on the site's 12-column grid and Woodward tokens; the branded
// Michroma face (same as the ticker) is reserved for headlines and
// section headers. The green accent appears only sparingly.
// ————————————————————————————————————————————————————————————————

const NYT_SMALL_BIZ =
  'https://www.nytimes.com/2026/07/17/business/economy/american-small-business-boom.html';

const LEAD_STORY = {
  headline: 'Remote work drives record productivity gains in Q1',
  dek: 'New data shows remote work — not AI alone — helped drive record U.S. labor productivity growth in Q1, and why remote work is becoming a competitive advantage.',
  slug: 'remote-work-drives-record-productivity-gains-in-q1',
};

// ——— In-site article pages (#/rwn/article/:slug) ———
// Body content adapted from the Roam Ideas original.
const ARTICLES = {
  'remote-work-drives-record-productivity-gains-in-q1': {
    breaking: true,
    headline: 'Remote work drives record productivity gains in Q1',
    caption: 'U.S. labor productivity, output and hours worked, indexed to 2019. Source: BLS.',
    authors: [{ name: 'Shelby Leimgruber', role: 'Head of Growth' }],
    date: 'July 17, 2026',
    sourceUrl: 'https://ro.am/ideas/remote-work-drives-record-productivity-gains-in-q1',
    body: [
      { type: 'lede', text: 'Remote work — not artificial intelligence — was the primary catalyst behind labor productivity’s exceptional first-quarter expansion, according to new data first reported by The New York Times.' },
      { type: 'p', text: 'The output generated by human labor increased at its fastest pace in more than two decades, even as hours worked stayed essentially flat — the clearest sign yet that how teams work is changing what they can produce.' },
      { type: 'h2', text: 'KKR sees remote work gains' },
      { type: 'p', text: '“I believe the productivity gains began coming out of Covid with the digitization of work, remote work, and the implementation of machine learning,” said Henry McVey, head of Global Macro and Asset Allocation at KKR.' },
      { type: 'h2', text: 'RWN’s take' },
      { type: 'p', text: 'Remote work converges three significant trends. First is worldwide talent accessibility, with platforms streamlining global hiring and team formation. Second involves AI and machine learning technologies that extract insights from digital work artifacts — meetings, communications, and presence. Third reflects the cultural influence of a generation of digital-native founders building companies with collaborative methods they pioneered in online communities.' },
      { type: 'quote', text: '“It’s all I’ve ever known … looking back I think gaming taught an entire generation how to collaborate remotely.”', cite: 'Alex Bouaziz, founder, Deel' },
      { type: 'p', text: 'The through-line: distributed teams aren’t trading productivity for flexibility anymore. The companies leaning into remote work — with the tooling to preserve presence, visibility, and spontaneous interaction — are the ones setting the pace.' },
    ],
  },
};

// ——— Lead chart data ———
// U.S. nonfarm business sector, indexed 2019 Q1 = 100, quarterly through
// 2026 Q1 (mirrors the chart in the Roam Ideas article). Output is derived:
// output = productivity × hours.
const CHART_PROD = [
  100, 100.4, 100.6, 101.1, 101.9, 104.2, 105.6, 106.4,
  108.3, 110.6, 111.7, 112.0, 111.4, 111.1, 111.5, 110.8,
  110.5, 111.4, 112.4, 113.7, 114.4, 114.1, 115.4, 116.4,
  116.9, 117.7, 118.5, 119.4, 120.3,
];
const CHART_HOURS = [
  100, 100.3, 100.5, 100.7, 99.4, 90.6, 95.6, 97.4,
  98.4, 99.7, 100.8, 101.6, 102.6, 103.5, 104.2, 104.8,
  105.2, 105.5, 105.7, 105.8, 105.9, 106.0, 106.0, 106.1,
  106.0, 106.1, 106.2, 106.1, 106.2,
];
const CHART_N = CHART_PROD.length;

// ——— Broadcast reels ———
// Real portrait YouTube Shorts (verified via the /shorts/ URL check);
// thumbnails come straight from YouTube, durations verified per video.
const BROADCAST_VIDEOS = [
  { id: 'i-xUS4Lfw3o', title: 'The Market of One', channel: 'Kleiner Perkins', duration: '0:32' },
  { id: 'TbZoqGkq_Ao', title: 'Is hybrid work the most profitable? Stanford’s Nick Bloom explains', channel: 'RWN', duration: '0:45' },
  { id: 'Piloy5ngQ94', title: 'How Fast Work Has Changed', channel: 'Kleiner Perkins', duration: '0:55' },
  { id: 'w0Xl_PVPyj4', title: 'Remote Work Secrets: How Nick Bloom Sees the Future of Work', channel: 'HerMoney', duration: '0:59' },
  { id: 'o3TrlHGRbFo', title: 'Remote employees are happier, according to a Gallup study', channel: 'Gallup study', duration: '0:41' },
];

// Smooth scrolling honors the user's reduced-motion preference.
const scrollBehavior = () =>
  window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth';

// Portrait thumb for Shorts; some don't have one — fall back to hqdefault.
const reelThumb = (id) => `https://i.ytimg.com/vi/${id}/oardefault.jpg`;
const reelThumbFallback = (e, id) => {
  if (!e.currentTarget.src.includes('hqdefault')) {
    e.currentTarget.src = `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
  }
};
const chartLabel = (i) => `Q${(i % 4) + 1} ${2019 + Math.floor(i / 4)}`;

function LeadChart() {
  const [hover, setHover] = useState(null);
  const svgRef = useRef(null);

  // Plot is flush with the panel's left padding edge — tick labels sit
  // ABOVE the grid lines (news-graphic style) so everything left-aligns
  // with the title and source line.
  const W = 560;
  const H = 560;
  const PL = 0;
  const PR = 104;
  const PT = 64;
  const PB = 44;
  const MIN = 88;
  const MAX = 130;

  const output = CHART_PROD.map((p, i) => (p * CHART_HOURS[i]) / 100);
  const x = (i) => PL + (i * (W - PL - PR)) / (CHART_N - 1);
  const y = (v) => PT + (H - PT - PB) * (1 - (v - MIN) / (MAX - MIN));
  const linePath = (data) => data.map((v, i) => `${i === 0 ? 'M' : 'L'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');

  const series = [
    { name: 'Output', data: output, accent: false },
    { name: 'Hours worked', data: CHART_HOURS, accent: false },
    { name: 'Productivity', data: CHART_PROD, accent: true },
  ];

  const onMove = (e) => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect) return;
    const fx = ((e.clientX - rect.left) / rect.width) * W;
    const idx = Math.round(((fx - PL) / (W - PL - PR)) * (CHART_N - 1));
    setHover(Math.max(0, Math.min(CHART_N - 1, idx)));
  };

  const ticks = [90, 100, 110, 120, 130];
  const yearIdxs = [0, 4, 8, 12, 16, 20, 24, 28];
  const tooltipLeft = hover !== null ? (x(hover) / W) * 100 : 0;
  const flip = hover !== null && hover > CHART_N * 0.55;

  return (
    <div className="rwn-lead-chartwrap">
      <div className="rwn-lead-chart-title text-caption-strong">U.S. labor productivity · index, 2019 = 100</div>
      <svg
        ref={svgRef}
        className="rwn-lead-chartsvg"
        viewBox={`0 0 ${W} ${H}`}
        role="img"
        aria-label="Productivity rising to 120 by Q1 2026 while hours worked stay flat"
        onPointerMove={onMove}
        onPointerLeave={() => setHover(null)}
      >
        {ticks.map((v) => (
          <g key={v}>
            <line x1={PL} x2={W - PR} y1={y(v)} y2={y(v)} className="rwn-ch-grid" />
            <text x={PL} y={y(v) - 7} textAnchor="start" className="rwn-ch-tick">{v}</text>
          </g>
        ))}
        {yearIdxs.map((i) => (
          <text key={i} x={x(i)} y={H - 18} textAnchor={i === 0 ? 'start' : 'middle'} className="rwn-ch-tick">{'’' + String(2019 + i / 4).slice(2)}</text>
        ))}

        {hover !== null && (
          <line x1={x(hover)} x2={x(hover)} y1={PT - 8} y2={H - PB} className="rwn-ch-guide" />
        )}

        {series.map((s) => (
          <g key={s.name}>
            <path d={linePath(s.data)} className={`rwn-ch-line ${s.accent ? 'rwn-ch-line-accent' : 'rwn-ch-line-dim'}`} />
            <text
              x={x(CHART_N - 1) + 10}
              y={y(s.data[CHART_N - 1]) + 3}
              className={`rwn-ch-label ${s.accent ? 'rwn-ch-label-accent' : ''}`}
            >
              {s.name}
            </text>
            {hover !== null && (
              <circle cx={x(hover)} cy={y(s.data[hover])} r="4" className={`rwn-ch-dot ${s.accent ? 'rwn-ch-dot-accent' : ''}`} />
            )}
          </g>
        ))}
      </svg>

      {hover !== null && (
        <div
          className="rwn-ch-tooltip"
          style={{ left: `${tooltipLeft}%`, transform: flip ? 'translate(calc(-100% - 14px), 0)' : 'translate(14px, 0)' }}
        >
          <div className="rwn-ch-tooltip-q text-caption-strong">{chartLabel(hover)}</div>
          {[...series].reverse().map((s) => (
            <div className="rwn-ch-tooltip-row text-caption" key={s.name}>
              <span className={`rwn-ch-tooltip-swatch ${s.accent ? 'rwn-ch-tooltip-swatch-accent' : ''}`} />
              <span className="rwn-ch-tooltip-name">{s.name}</span>
              <span className="rwn-ch-tooltip-val">{s.data[hover].toFixed(1)}</span>
            </div>
          ))}
        </div>
      )}

      <div className="rwn-lead-chart-source text-caption">Source: BLS · Roam Ideas</div>
    </div>
  );
}

const TOP_STORIES = [
  {
    tag: 'PRODUCTIVITY',
    headline: 'Working from home is powering productivity, argues Stanford economist Nicholas Bloom',
    source: 'IMF Finance & Development',
    url: 'https://www.imf.org/en/publications/fandd/issues/2024/09/working-from-home-is-powering-productivity-bloom',
  },
  {
    tag: 'RESEARCH',
    headline: 'Hybrid working from home improves retention without damaging performance',
    source: 'Nature',
    url: 'https://www.nature.com/articles/s41586-024-07500-2',
  },
  {
    tag: 'TRENDING',
    headline: 'American small business boom fueled by a new generation of remote founders',
    source: 'The New York Times',
    url: NYT_SMALL_BIZ,
  },
  {
    tag: 'ECONOMY',
    headline: 'Working from home saves commuters 72 minutes a day, global study finds',
    source: 'NBER',
    url: 'https://www.nber.org/papers/w30866',
  },
  {
    tag: 'IMPACT',
    headline: 'Remote work helps push disabled employment to a record high',
    source: 'Fortune',
    url: 'https://fortune.com/2023/02/24/remote-work-disabled-employment-record-high-remote-work-office-mandates/',
  },
  {
    tag: 'DATA',
    headline: 'More than one-third of U.S. employees still work from home, new research shows',
    source: 'CNBC',
    url: 'https://www.cnbc.com/2026/07/01/employees-work-from-home-despite-stricter-policies.html',
  },
];

const SECTIONS = [
  {
    title: 'Data & Trends',
    stories: [
      {
        headline: 'Remote and hybrid workers report the highest rates of thriving at work',
        source: 'Gallup',
        url: 'https://www.gallup.com/topic/remote-work.aspx',
      },
      {
        headline: 'Remote and hybrid work stabilize at their highest non-pandemic levels on record',
        source: 'Robert Half',
        url: 'https://www.roberthalf.com/us/en/insights/research/remote-work-statistics-and-trends',
      },
      {
        headline: 'The remote work economy keeps growing — tracking a rising remote job market',
        source: 'FlexJobs',
        url: 'https://www.flexjobs.com/blog/post/flexjobs-remote-work-economy-index',
      },
    ],
  },
  {
    title: 'Companies',
    stories: [
      {
        headline: 'Atlassian and Airbnb double down on remote work as peers order office returns',
        source: 'Bloomberg Law',
        url: 'https://news.bloomberglaw.com/daily-labor-report/atlassian-airbnb-boost-remote-work-as-peers-order-office-return',
      },
      {
        headline: 'Hybrid work cuts attrition by a third — with no hit to promotions or performance',
        source: 'Fortune',
        url: 'https://fortune.com/2024/06/18/stanford-nick-bloom-hybrid-work-cuts-attrition-no-negative-impact-promoted/',
      },
      {
        headline: 'Hybrid work is a “win-win-win” for companies and workers, Stanford study finds',
        source: 'Stanford Report',
        url: 'https://news.stanford.edu/stories/2024/06/hybrid-work-is-a-win-win-win-for-companies-workers',
      },
    ],
  },
  {
    title: 'Economy & Policy',
    stories: [
      {
        headline: 'Remote work is enabling record employment among workers with disabilities',
        source: 'Economic Innovation Group',
        url: 'https://eig.org/remote-work-is-enabling-higher-employment-among-disabled-workers/',
      },
      {
        headline: 'Commute time savings — work from home hands hours back to the global workforce',
        source: 'CEPR / VoxEU',
        url: 'https://cepr.org/voxeu/columns/commute-time-savings-when-working-home',
      },
      {
        headline: 'Work from home settles into a durable, decades-defining shift, economists find',
        source: 'Journal of Economic Perspectives',
        url: 'https://www.aeaweb.org/articles?id=10.1257/jep.37.4.23',
      },
    ],
  },
];

// Bloomberg-style "Today's Videos" card for the rail: one portrait reel at a
// time, autoplaying muted, with dot pagination + prev/next arrows.
function RailVideos() {
  const [idx, setIdx] = useState(0);
  const [muted, setMuted] = useState(true);
  const [fading, setFading] = useState(false);
  const mutedRef = useRef(true);
  mutedRef.current = muted;
  const frameRef = useRef(null);
  const endedRef = useRef(false);
  const fadeTimerRef = useRef(0);
  const v = BROADCAST_VIDEOS[idx];

  // Fade out (150ms transition retargets under rapid paging), then swap
  // the video and fade back in — no hard cut.
  const paginate = (update) => {
    setFading(true);
    clearTimeout(fadeTimerRef.current);
    fadeTimerRef.current = setTimeout(() => {
      setIdx(update);
      setFading(false);
    }, 150);
  };
  useEffect(() => () => clearTimeout(fadeTimerRef.current), []);

  const go = (i) => paginate((i + BROADCAST_VIDEOS.length) % BROADCAST_VIDEOS.length);

  // YouTube force-enables captions on muted autoplay — keep unloading the
  // captions module (it re-arms on video changes). The same tick sends the
  // widget-API "listening" handshake so the player streams us state events,
  // and enforces the current mute preference across video changes.
  useEffect(() => {
    const timer = setInterval(() => {
      if (document.hidden) return;
      const win = frameRef.current?.contentWindow;
      if (!win) return;
      win.postMessage(JSON.stringify({ event: 'listening', id: 'rwn-rail', channel: 'widget' }), '*');
      win.postMessage(JSON.stringify({ event: 'command', func: mutedRef.current ? 'mute' : 'unMute', args: [] }), '*');
      ['captions', 'cc'].forEach((module) => {
        win.postMessage(JSON.stringify({ event: 'command', func: 'unloadModule', args: [module] }), '*');
      });
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  // Advance to the next video when the current one ends (player state 0).
  useEffect(() => {
    endedRef.current = false;
  }, [idx]);

  useEffect(() => {
    const onMessage = (e) => {
      if (e.source !== frameRef.current?.contentWindow || typeof e.data !== 'string') return;
      let data;
      try {
        data = JSON.parse(e.data);
      } catch {
        return;
      }
      const state = data.event === 'onStateChange' ? data.info
        : data.event === 'infoDelivery' ? data.info?.playerState
        : null;
      if (state === 0 && !endedRef.current) {
        endedRef.current = true;
        paginate((prev) => (prev + 1) % BROADCAST_VIDEOS.length);
      }
    };
    window.addEventListener('message', onMessage);
    return () => window.removeEventListener('message', onMessage);
  }, []);

  return (
    <div className="rwn-rail-videos">
      <h2 className="rwn-kicker rwn-rail-videos-kicker text-caption-strong">
        <span className="rwn-kicker-logo" aria-hidden="true" />
        <span className="rwn-kicker-text">Today’s Video</span>
      </h2>
      <div className="rwn-rail-video-card">
        <div className="rwn-rail-video-media" data-fading={fading || undefined}>
          <iframe
            ref={frameRef}
            key={v.id}
            className="rwn-reel-player"
            src={`https://www.youtube-nocookie.com/embed/${v.id}?autoplay=1&mute=1&controls=0&playsinline=1&rel=0&cc_load_policy=3&iv_load_policy=3&enablejsapi=1`}
            title={v.title}
            allow="autoplay; encrypted-media; picture-in-picture"
            allowFullScreen
          />
          <span className="rwn-reel-shade" aria-hidden="true" />
          <button
            className="rwn-reel-mute"
            onClick={() => {
              const next = !muted;
              setMuted(next);
              frameRef.current?.contentWindow?.postMessage(
                JSON.stringify({ event: 'command', func: next ? 'mute' : 'unMute', args: [] }),
                '*',
              );
            }}
            aria-label={muted ? 'Unmute' : 'Mute'}
          >
            {muted ? (
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                <path d="M8 3L4.5 5.5H2V10.5H4.5L8 13V3Z" stroke="white" strokeWidth="1.5" strokeLinejoin="round" fill="none" />
                <path d="M11 6L14 9M14 6L11 9" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
              </svg>
            ) : (
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                <path d="M8 3L4.5 5.5H2V10.5H4.5L8 13V3Z" stroke="white" strokeWidth="1.5" strokeLinejoin="round" fill="none" />
                <path d="M11 5.5C11.6 6.2 12 7.05 12 8C12 8.95 11.6 9.8 11 10.5" stroke="white" strokeWidth="1.5" strokeLinecap="round" fill="none" />
                <path d="M12.5 3.5C13.75 4.75 14.5 6.3 14.5 8C14.5 9.7 13.75 11.25 12.5 12.5" stroke="white" strokeWidth="1.5" strokeLinecap="round" fill="none" />
              </svg>
            )}
          </button>
          <span className="rwn-reel-bottom">
            <span className="rwn-reel-title text-headline">{v.title}</span>
            <span className="rwn-rail-video-bug" aria-label="RWN">
              <span className="rwn-rail-video-bug-logo" />
            </span>
          </span>
        </div>
      </div>
      <div className="rwn-rail-videos-foot">
        <div className="rwn-rail-video-dots">
          {BROADCAST_VIDEOS.map((b, i) => (
            <button
              key={b.id}
              className={`rwn-rail-video-dot ${i === idx ? 'rwn-rail-video-dot-active' : ''}`}
              onClick={() => go(i)}
              aria-label={`Video ${i + 1} of ${BROADCAST_VIDEOS.length}`}
            />
          ))}
        </div>
        <div className="rwn-reels-nav">
          <button className="rwn-reels-arrow" aria-label="Previous video" onClick={() => go(idx - 1)}>
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
              <path d="M8.5 3 L4.5 7 L8.5 11" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </button>
          <button className="rwn-reels-arrow" aria-label="Next video" onClick={() => go(idx + 1)}>
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
              <path d="M5.5 3 L9.5 7 L5.5 11" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
}

// Right-edge dev controls — same capsules as the feature pages.
function RightControls({ theme, onToggleTheme, showGrid, onToggleGrid }) {
  return (
    <div className="sc-right-controls">
      <button
        type="button"
        className="unbutton sc-theme-capsule"
        onClick={onToggleTheme}
        aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`}
        aria-pressed={theme === 'light'}
      >
        <span className={`sc-theme-capsule-knob ${theme === 'light' ? 'bottom' : ''}`} aria-hidden="true" />
        <span className={`sc-theme-capsule-icon ${theme === 'dark' ? 'active' : ''}`} aria-hidden="true">
          <svg width="14" height="14" viewBox="0 0 16 16" fill="none"><path d="M14 8.5C13.3 12.1 10 14.5 6.5 13.5C3 12.5 1 9.5 2 6C2.8 3.2 5.5 1.5 8.5 2C7 3.5 6.5 6 8 8.5C9 10 11 11 14 8.5Z" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" /></svg>
        </span>
        <span className={`sc-theme-capsule-icon ${theme === 'light' ? 'active' : ''}`} aria-hidden="true">
          <svg width="14" height="14" viewBox="0 0 16 16" fill="none"><circle cx="8" cy="8" r="3" stroke="currentColor" strokeWidth="1.3" /><path d="M8 2V3.5M8 12.5V14M2 8H3.5M12.5 8H14M3.8 3.8L4.8 4.8M11.2 11.2L12.2 12.2M3.8 12.2L4.8 11.2M11.2 4.8L12.2 3.8" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" /></svg>
        </span>
      </button>
      <button
        type="button"
        className="unbutton sc-grid-capsule"
        onClick={onToggleGrid}
        title="Toggle 12-column grid"
        aria-label="Toggle 12-column grid"
        aria-pressed={showGrid}
      >
        <span className={`sc-grid-capsule-knob ${showGrid ? 'on' : ''}`} aria-hidden="true" />
        <span className={`sc-grid-capsule-icon ${!showGrid ? 'active' : ''}`} aria-hidden="true">
          <svg width="14" height="14" viewBox="0 0 16 16" fill="none"><rect x="2.5" y="2.5" width="11" height="11" stroke="currentColor" strokeWidth="1.3" rx="1.5" /></svg>
        </span>
        <span className={`sc-grid-capsule-icon ${showGrid ? 'active' : ''}`} aria-hidden="true">
          <svg width="14" height="14" viewBox="0 0 16 16" fill="none"><rect x="2.5" y="2.5" width="11" height="11" stroke="currentColor" strokeWidth="1.3" rx="1.5" /><path d="M6 2.5V13.5M10 2.5V13.5M2.5 6H13.5M2.5 10H13.5" stroke="currentColor" strokeWidth="1" /></svg>
        </span>
      </button>
    </div>
  );
}

// BBC-style article layout: headline, media + caption, byline, dated body.
function ArticleView({ article }) {
  return (
    <main className="rwn-article-main">
      <div className="rwn-grid">
        <article className="rwn-article">
          <a className="rwn-article-back text-subheadline-emphasis" href="#/rwn">
            <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
              <path d="M7.5 2.5 L4 6 L7.5 9.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            Back
          </a>
          {article.breaking && (
            <div className="rwn-kicker rwn-breaking-kicker text-caption-strong" aria-label="Breaking news">
              <span className="rwn-breaking-tag">
                <span className="rwn-breaking-dot" aria-hidden="true" />
                <span className="rwn-kicker-text">Breaking</span>
              </span>
            </div>
          )}
          <h1 className="rwn-article-headline">{article.headline}</h1>
          <div className="rwn-lead-visual">
            <LeadChart />
          </div>
          <div className="rwn-article-caption text-caption">{article.caption}</div>
          <div className="rwn-article-byline text-subheadline">
            {article.authors.map((a, i) => (
              <span key={a.name}>
                {i > 0 && ' and '}
                <strong>{a.name}</strong>, {a.role}
              </span>
            ))}
          </div>
          <div className="rwn-article-date text-caption">{article.date}</div>
          <div className="rwn-article-body">
            {article.body.map((block, i) => {
              if (block.type === 'h2') return <h2 key={i} className="rwn-article-h2">{block.text}</h2>;
              if (block.type === 'lede') return <p key={i} className="rwn-article-lede text-body-strong">{block.text}</p>;
              if (block.type === 'quote') {
                return (
                  <blockquote key={i} className="rwn-article-quote">
                    <p className="text-body">{block.text}</p>
                    <cite className="text-caption">{block.cite}</cite>
                  </blockquote>
                );
              }
              return <p key={i} className="rwn-article-p text-body">{block.text}</p>;
            })}
          </div>
          <a className="rwn-article-source text-subheadline-strong" href={article.sourceUrl} target="_blank" rel="noopener noreferrer">
            Read the original on Roam Ideas ↗
          </a>
        </article>
      </div>
    </main>
  );
}

const getArticleSlug = () => {
  const m = window.location.hash.match(/^#\/rwn\/article\/([a-z0-9-]+)/i);
  return m ? m[1] : null;
};

export default function RWNPage() {
  const [email, setEmail] = useState('');
  const [subscribed, setSubscribed] = useState(false);
  const newsletterRef = useRef(null);
  const reelsRef = useRef(null);
  const [playingReel, setPlayingReel] = useState(null);

  // RWN owns the theme while mounted (same pattern as FeaturePage):
  // publish it on <html> so the ticker and global rules flip too, and
  // seed from whatever theme the previous page left behind.
  const [theme, setTheme] = useState(
    () => document.documentElement.getAttribute('data-theme') || 'dark',
  );
  const rootRef = useRef(null);
  useEffect(() => {
    const html = document.documentElement;
    html.classList.add('theme-switching');
    html.setAttribute('data-theme', theme);
    const raf = requestAnimationFrame(() => {
      requestAnimationFrame(() => html.classList.remove('theme-switching'));
    });
    return () => {
      cancelAnimationFrame(raf);
      html.classList.remove('theme-switching');
      html.removeAttribute('data-theme');
    };
  }, [theme]);

  // 12-column debug grid, shared with the rest of the site via
  // localStorage + the toggle-grid event.
  const [showGrid, setShowGrid] = useState(() => {
    try { return localStorage.getItem('showGrid') === 'true'; } catch { return false; }
  });
  useEffect(() => {
    try { localStorage.setItem('showGrid', showGrid); } catch {}
  }, [showGrid]);
  useEffect(() => {
    const handler = () => setShowGrid(g => !g);
    const syncHandler = (e) => { if (e.key === 'showGrid') setShowGrid(e.newValue === 'true'); };
    window.addEventListener('toggle-grid', handler);
    window.addEventListener('storage', syncHandler);
    return () => {
      window.removeEventListener('toggle-grid', handler);
      window.removeEventListener('storage', syncHandler);
    };
  }, []);

  // Article sub-route (#/rwn/article/:slug) — falls back to the hub for
  // unknown slugs.
  const [articleSlug, setArticleSlug] = useState(getArticleSlug);
  useEffect(() => {
    const onHash = () => setArticleSlug(getArticleSlug());
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, []);
  const article = articleSlug ? ARTICLES[articleSlug] : null;
  useEffect(() => {
    rootRef.current?.scrollTo(0, 0);
    window.scrollTo(0, 0);
  }, [articleSlug]);

  // Homepage-style nav: transparent at the top, solid bg once scrolled.
  // The sc-navbar-wrap CSS keys off data-logo-visible. The page scrolls
  // inside .sc-viewport, so listen there.
  const [navSolid, setNavSolid] = useState(false);
  useEffect(() => {
    const el = rootRef.current;
    if (!el) return;
    const onScroll = () => setNavSolid(el.scrollTop >= 200);
    onScroll();
    el.addEventListener('scroll', onScroll, { passive: true });
    return () => el.removeEventListener('scroll', onScroll);
  }, []);

  const scrollReels = (dir) => {
    const el = reelsRef.current;
    if (el) el.scrollBy({ left: dir * el.clientWidth, behavior: scrollBehavior() });
  };



  // Hash anchors would clobber the app's hash routing — scroll imperatively.
  const scrollTo = (ref) => ref.current?.scrollIntoView({ behavior: scrollBehavior(), block: 'start' });

  const subscribe = (e) => {
    e.preventDefault();
    if (!email.trim()) return;
    setSubscribed(true);
  };

  return (
    <div ref={rootRef} className="sc-viewport rwn-page" data-theme={theme}>
      {showGrid && (
        <div className="sc-grid-debug">
          {Array.from({ length: 12 }).map((_, i) => <div key={i} className="sc-grid-debug-col" />)}
        </div>
      )}
      {/* ——— Site nav (same fixed navbar as the rest of the site) ——— */}
      <div className="sc-navbar-wrap" data-logo-visible={navSolid}>
        <Navbar />
      </div>
      <RightControls
        theme={theme}
        onToggleTheme={() => setTheme(t => t === 'dark' ? 'light' : 'dark')}
        showGrid={showGrid}
        onToggleGrid={() => setShowGrid(g => !g)}
      />

      {/* ——— Masthead (hub only — article pages go straight to content) ——— */}
      {!article && (
      <header className="rwn-masthead">
        <div className="rwn-grid">
          <div className="rwn-masthead-inner">
            <div className="rwn-brand">
              <span className="rwn-brand-logo" role="img" aria-label="RWN" />
              <div className="rwn-brand-words">
                <span className="rwn-brand-name text-caption-strong">Remote Work News</span>
                <span className="rwn-brand-owner text-caption">by <strong>Roam</strong></span>
              </div>
            </div>
          </div>
        </div>
      </header>
      )}

      {article ? (
        <ArticleView article={article} />
      ) : (
      <main>
        {/* ——— Lead story + rail ——— */}
        <section className="rwn-lead-band">
          <div className="rwn-grid">
            <article className="rwn-lead-story">
              <div className="rwn-kicker rwn-breaking-kicker text-caption-strong" aria-label="Breaking news">
                <span className="rwn-breaking-tag">
                  <span className="rwn-breaking-dot" aria-hidden="true" />
                  <span className="rwn-kicker-text">Breaking</span>
                </span>
              </div>
              <a className="rwn-lead-link" href={`#/rwn/article/${LEAD_STORY.slug}`}>
                <h1 className="rwn-lead-headline">{LEAD_STORY.headline}</h1>
              </a>
              <div className="rwn-lead-visual">
                <LeadChart />
              </div>
              <p className="rwn-lead-dek text-body">{LEAD_STORY.dek}</p>
            </article>

            <aside className="rwn-rail">
              <RailVideos />
            </aside>

            <div className="rwn-lead-topstories">
              <h2 className="rwn-kicker rwn-topstories-kicker text-caption-strong">
                <span className="rwn-kicker-logo" aria-hidden="true" />
                <span className="rwn-kicker-text">Top Stories</span>
              </h2>
              <ol className="rwn-rail-list">
                {TOP_STORIES.map((s, i) => {
                  const Tag = s.url ? 'a' : 'div';
                  return (
                    <li key={i}>
                      <Tag
                        className="rwn-rail-item"
                        {...(s.url && { href: s.url, target: '_blank', rel: 'noopener noreferrer' })}
                      >
                        <span className="rwn-rail-num">{String(i + 1).padStart(2, '0')}</span>
                        <span className="rwn-rail-body">
                          <span className="rwn-rail-tag text-caption-2-strong">{s.tag}</span>
                          <span className="rwn-rail-headline text-subheadline-strong">{s.headline}</span>
                          <span className="rwn-rail-source text-caption">{s.source}</span>
                        </span>
                      </Tag>
                    </li>
                  );
                })}
              </ol>
            </div>
          </div>
        </section>

        {/* ——— Broadcast — portrait reels row ——— */}
        <section className="rwn-broadcast-band">
          <div className="rwn-grid">
            <div className="rwn-broadcast-head">
              <div className="rwn-kicker text-caption-strong">
                <span className="rwn-kicker-logo" aria-hidden="true" />
                <span className="rwn-kicker-text">Video</span>
              </div>
              <div className="rwn-reels-nav">
                <button className="rwn-reels-arrow" aria-label="Previous videos" onClick={() => scrollReels(-1)}>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                    <path d="M8.5 3 L4.5 7 L8.5 11" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </button>
                <button className="rwn-reels-arrow" aria-label="Next videos" onClick={() => scrollReels(1)}>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                    <path d="M5.5 3 L9.5 7 L5.5 11" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </button>
              </div>
            </div>
            <div className="rwn-reels" ref={reelsRef}>
              {BROADCAST_VIDEOS.map((v) => (
                <div className="rwn-reel" key={v.id}>
                  {playingReel === v.id && (
                    <iframe
                      className="rwn-reel-player"
                      src={`https://www.youtube-nocookie.com/embed/${v.id}?autoplay=1&playsinline=1&rel=0&cc_load_policy=3&iv_load_policy=3`}
                      title={v.title}
                      allow="autoplay; encrypted-media; picture-in-picture"
                      allowFullScreen
                    />
                  )}
                  {(
                    <button
                      className={`rwn-reel-cover ${playingReel === v.id ? 'rwn-reel-cover-hidden' : ''}`}
                      onClick={() => setPlayingReel(v.id)}
                      aria-label={`Play: ${v.title}`}
                      aria-hidden={playingReel === v.id || undefined}
                      tabIndex={playingReel === v.id ? -1 : undefined}
                    >
                      <img
                        className="rwn-reel-thumb"
                        src={reelThumb(v.id)}
                        onError={(e) => reelThumbFallback(e, v.id)}
                        alt=""
                        loading="lazy"
                      />
                      <span className="rwn-reel-shade" aria-hidden="true" />
                      <span className="rwn-reel-play rwn-reel-play-center" aria-hidden="true">
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                          <path d="M4.5 2.8 L11 7 L4.5 11.2 Z" fill="currentColor" />
                        </svg>
                      </span>
                      <span className="rwn-reel-bottom">
                        <span className="rwn-reel-title text-headline">{v.title}</span>
                        <span className="rwn-reel-channel text-caption">{v.channel}</span>
                      </span>
                    </button>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ——— Newsletter ——— */}
        <section className="rwn-newsletter-band" ref={newsletterRef}>
          <div className="rwn-grid">
            <div className="rwn-newsletter">
              <div className="rwn-newsletter-text">
                <div className="rwn-kicker text-caption-strong">
                  <span className="rwn-kicker-logo" aria-hidden="true" />
                  <span className="rwn-kicker-text">Newsletter</span>
                </div>
                <h2 className="rwn-newsletter-title">The Friday Brief</h2>
                <p className="rwn-newsletter-sub text-body">
                  The week in remote work — the stories, the data, and what they mean.
                  Every Friday morning. Read in five minutes.
                </p>
              </div>
              {subscribed ? (
                <div className="rwn-newsletter-done text-body-strong">
                  <span className="rwn-newsletter-check" aria-hidden="true">✓</span>
                  You&rsquo;re on the list. See you Friday.
                </div>
              ) : (
                <form className="rwn-newsletter-form" onSubmit={subscribe}>
                  <input
                    type="email"
                    required
                    className="rwn-newsletter-input text-subheadline"
                    placeholder="you@company.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    aria-label="Email address"
                  />
                  <button type="submit" className="rwn-newsletter-btn">Subscribe</button>
                </form>
              )}
            </div>
          </div>
        </section>

        {/* ——— Section grid ——— */}
        <section className="rwn-sections-band">
          <div className="rwn-grid">
            {SECTIONS.map((sec) => (
              <div className="rwn-section-col" key={sec.title}>
                <h3 className="rwn-section-header">{sec.title}</h3>
                <ul className="rwn-section-list">
                  {sec.stories.map((s, i) => {
                    const Tag = s.url ? 'a' : 'div';
                    return (
                      <li key={i}>
                        <Tag
                          className="rwn-section-item"
                          {...(s.url && { href: s.url, target: '_blank', rel: 'noopener noreferrer' })}
                        >
                          <span className="rwn-section-headline text-subheadline-strong">{s.headline}</span>
                          <span className="rwn-section-meta text-caption">{s.source}</span>
                        </Tag>
                      </li>
                    );
                  })}
                </ul>
              </div>
            ))}
          </div>
        </section>

      </main>
      )}

    </div>
  );
}
